/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AutoSlider: typeof import('./components/common/AutoSlider.vue')['default']
    CardSilder: typeof import('./components/common/CardSilder.vue')['default']
    DiagramItem: typeof import('./components/project/DiagramItem.vue')['default']
    EditAccountInfoDialog: typeof import('./components/common/EditAccountInfoDialog.vue')['default']
    FileUpload: typeof import('./components/FileUpload.vue')['default']
    FullScreenSlider: typeof import('./components/common/FullScreenSlider.vue')['default']
    HeaderDrawer: typeof import('./components/common/HeaderDrawer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginDialog: typeof import('./components/common/LoginDialog.vue')['default']
    MovieItem: typeof import('./components/common/MovieItem.vue')['default']
    NaldFooter: typeof import('./components/common/NaldFooter.vue')['default']
    NaldHeader: typeof import('./components/common/NaldHeader.vue')['default']
    ProjectDiagram: typeof import('./components/project/ProjectDiagram.vue')['default']
    ProjectHistory: typeof import('./components/project/ProjectHistory.vue')['default']
    ProjectKube: typeof import('./components/project/ProjectKube.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
