/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DiagramItem: typeof import('./components/project/DiagramItem.vue')['default']
    EditAccountInfoDialog: typeof import('./components/dialog/EditAccountInfoDialog.vue')['default']
    FileUpload: typeof import('./components/wonderwall/video/FileUpload.vue')['default']
    HeaderDrawer: typeof import('./components/common/HeaderDrawer.vue')['default']
    LoginDialog: typeof import('./components/dialog/LoginDialog.vue')['default']
    MovieItem: typeof import('./components/wonderwall/video/MovieItem.vue')['default']
    NaldFooter: typeof import('./components/common/NaldFooter.vue')['default']
    NaldHeader: typeof import('./components/common/NaldHeader.vue')['default']
    ProjectDiagram: typeof import('./components/project/ProjectDiagram.vue')['default']
    ProjectHistory: typeof import('./components/project/ProjectHistory.vue')['default']
    ProjectKube: typeof import('./components/project/ProjectKube.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Subtitles: typeof import('./components/wonderwall/video/Subtitles.vue')['default']
    TerminalItem: typeof import('./components/terminal/TerminalItem.vue')['default']
    VideoPlayer: typeof import('./components/wonderwall/video/VideoPlayer.vue')['default']
    VideoSlider: typeof import('./components/wonderwall/video/VideoSlider.vue')['default']
  }
}
