/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/aboutMe/AboutMePage': RouteRecordInfo<'/aboutMe/AboutMePage', '/aboutMe/AboutMePage', Record<never, never>, Record<never, never>>,
    '/contact/ContactPage': RouteRecordInfo<'/contact/ContactPage', '/contact/ContactPage', Record<never, never>, Record<never, never>>,
    '/FileUpload': RouteRecordInfo<'/FileUpload', '/FileUpload', Record<never, never>, Record<never, never>>,
    '/MainPage': RouteRecordInfo<'/MainPage', '/MainPage', Record<never, never>, Record<never, never>>,
    '/project/ProjectPage': RouteRecordInfo<'/project/ProjectPage', '/project/ProjectPage', Record<never, never>, Record<never, never>>,
    '/wonderwall/sandbox/SandboxPage': RouteRecordInfo<'/wonderwall/sandbox/SandboxPage', '/wonderwall/sandbox/SandboxPage', Record<never, never>, Record<never, never>>,
    '/wonderwall/sandbox/SandboxTerminalPage': RouteRecordInfo<'/wonderwall/sandbox/SandboxTerminalPage', '/wonderwall/sandbox/SandboxTerminalPage', Record<never, never>, Record<never, never>>,
    '/wonderwall/streaming/StreamingListPage': RouteRecordInfo<'/wonderwall/streaming/StreamingListPage', '/wonderwall/streaming/StreamingListPage', Record<never, never>, Record<never, never>>,
    '/wonderwall/streaming/StreamingPage': RouteRecordInfo<'/wonderwall/streaming/StreamingPage', '/wonderwall/streaming/StreamingPage', Record<never, never>, Record<never, never>>,
    '/wonderwall/WonderwallPage': RouteRecordInfo<'/wonderwall/WonderwallPage', '/wonderwall/WonderwallPage', Record<never, never>, Record<never, never>>,
  }
}
